
application:
  params:
    bootstrap-server: localhost:9092
    group-id: grp-test-producer
    client-id: producer-client
    auto-offset-reset: earliest
    producer-topic: online-sales

server:
  port: 8081